import Head from "next/head";
import Navbar from "@/components/navbar/Navbar";
import Button from "@/components/button/Button";
import styles from "../styles/Home.module.css";
import Router from "next/router";
import Maping from "@/components/mapping/Maping";
import axios from "axios";

export default function Home({ trips }) {
  const onClickHandler = () => {};
  return (
    <>
      <Head>
        <title>MAKALIUS atsiskaitymui</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar text={"Makalius"} />
        <div className={styles.buttonWraper}>
          <Button
            text={"Create Holiday"}
            onClick={() => Router.push("/insertTrip/")}
          />
        </div>

        <div className={styles.infoBox}>
          {trips.map((trip) => {
            return <Maping trip={trip} />;
          })}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(contex) {
  // console.log("contex", contex);

  const response = await axios.get(
    "https://63e3caca619fce55d4219490.mockapi.io/trips"
  );

  return {
    props: {
      trips: response.data,
    },
  };
}
